# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialNetworkApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialNetworkApp
  pod 'Firebase'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'FirebaseAuth'
  pod 'SDWebImage', '~>3.8'
end
